# Overlay Development Image for TurtleBot3 Simulation
FROM turtlebot3_overlay:latest
RUN source /opt/ros/noetic/setup.bash
# # install miniconda
# FROM ubuntu:20.04
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update

RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

ENV PATH="/root/miniconda3/bin:$PATH"

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 
RUN conda --version

SHELL ["/bin/bash", "--login", "-c"]
RUN conda create --name py3_6 python=3.6 
RUN conda init bash 
RUN echo "conda activate py3_6" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]
RUN source ~/miniconda3/etc/profile.d/conda.sh \
    && conda activate py3_6 \
    && conda install pip \
    && pip install pip install Cmake\
    && pip install opencv-python==3.4.2.17 \
    && pip install opencv-contrib-python==3.4.2.17 \
    && pip install PyYAML \
    && pip install rospkg \
    && pip install empy

RUN conda config --set auto_activate_base false
RUN echo "conda deactivate" >> ~/.bashrc
#  && cd /overlay_ws \
#  && catkin config --extend /turtlebot3_ws/devel \
#  && catkin build

# Set up the work directory and entrypoint
WORKDIR /overlay_ws
COPY ./docker/entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
