# Base Image for TurtleBot3 Simulation
FROM nvidia_ros:latest
SHELL ["/bin/bash", "-c"]

# Install basic apt packages
RUN apt-get update && apt-get install -y \
  cmake \
  g++ \
  git \
  gnupg gnupg1 gnupg2 \
  libcanberra-gtk* \
  python3-catkin-tools \
  python3-pip \
  python3-tk \
  wget

RUN apt install vim
# Install additional ROS packages
RUN apt-get install -y \
  ros-noetic-gmapping \
  ros-noetic-navigation \
  ros-noetic-py-trees \
  ros-noetic-py-trees-ros \
  ros-noetic-rqt-py-trees

# Remove display warnings
RUN mkdir /tmp/runtime-root
ENV XDG_RUNTIME_DIR "/tmp/runtime-root"
ENV NO_AT_BRIDGE 1

# Set up the work directory and entrypoint
WORKDIR /turtlebot3_ws
COPY ./docker/entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
